spring.application.name=library-management-system

logging.structured.format.console=ecs

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/library_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:library_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:library_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=100

server.port=8080